# -*- coding: utf-8 -*-
"""TOEIC 빈출 어휘 -> data/words_toeic.js 생성
- 영어단어장.csv(내 단어장)와 중복되는 단어는 자동 제외
- 실행: python build_toeic.py
"""
import csv, json, os

BASE = os.path.dirname(os.path.abspath(__file__))

# (단어, 발음기호, 뜻, 예문) — TOEIC 주제별 빈출 어휘
TOEIC = [
    # ===== 사무 / 조직 =====
    ("colleague", "/ˈkɑliːɡ/", "동료", "She discussed the schedule change with her colleagues."),
    ("supervisor", "/ˈsuːpərvaɪzər/", "감독관, 상사", "Please submit the report to your supervisor by Friday."),
    ("subordinate", "/səˈbɔːrdənət/", "부하 직원", "A good manager listens carefully to his subordinates."),
    ("executive", "/ɪɡˈzɛkjətɪv/", "임원, 경영진", "The executives will meet to discuss the merger next week."),
    ("headquarters", "/ˈhɛdkwɔːrtərz/", "본사, 본부", "The company moved its headquarters to Seoul last year."),
    ("branch", "/bræntʃ/", "지사, 지점", "Our bank opened a new branch in the downtown area."),
    ("division", "/dɪˈvɪʒən/", "(회사의) 부서, 사업부", "He was transferred to the overseas sales division."),
    ("subsidiary", "/səbˈsɪdiˌɛri/", "자회사", "The corporation owns several subsidiaries in Asia."),
    ("affiliate", "/əˈfɪliət/", "계열사, 제휴사", "Our affiliates in Europe will handle the distribution."),
    ("corporation", "/ˌkɔːrpəˈreɪʃən/", "법인, 대기업", "The corporation announced record profits this quarter."),
    ("enterprise", "/ˈɛntərˌpraɪz/", "기업, 사업", "Small enterprises often struggle to secure funding."),
    ("firm", "/fɜːrm/", "회사 (특히 법률/회계)", "She joined a law firm right after graduation."),
    ("founder", "/ˈfaʊndər/", "설립자, 창업자", "The founder of the company will retire next month."),
    ("committee", "/kəˈmɪti/", "위원회", "The hiring committee will review all applications."),
    ("personnel", "/ˌpɜːrsəˈnɛl/", "직원들, 인사과", "All personnel must attend the safety training session."),
    ("workforce", "/ˈwɜːrkfɔːrs/", "노동력, 전 직원", "The factory reduced its workforce by ten percent."),
    ("receptionist", "/rɪˈsɛpʃənɪst/", "접수 담당자", "The receptionist will direct you to the meeting room."),
    ("intern", "/ˈɪntɜːrn/", "인턴, 수습사원", "The interns will be trained for two weeks before starting."),
    ("employer", "/ɪmˈplɔɪər/", "고용주", "Her employer offered her a generous benefits package."),
    ("employee", "/ɪmˈplɔɪiː/", "직원, 종업원", "All employees are required to wear identification badges."),
    ("occupation", "/ˌɑkjəˈpeɪʃən/", "직업", "Please state your name and occupation on the form."),
    ("profession", "/prəˈfɛʃən/", "(전문적인) 직업", "Teaching is considered a highly respected profession."),
    ("task", "/tæsk/", "업무, 과제", "Completing the inventory check is your first task today."),
    ("assignment", "/əˈsaɪnmənt/", "배정된 업무, 임무", "He accepted an overseas assignment in Singapore."),
    ("workload", "/ˈwɜːrkloʊd/", "업무량", "We hired more staff to reduce the team's workload."),
    ("workplace", "/ˈwɜːrkpleɪs/", "직장, 업무 현장", "The new policy aims to improve workplace safety."),
    ("headquarter", "/ˈhɛdkwɔːrtər/", "본사를 두다", "The firm is headquartered in downtown Chicago."),
    ("duty", "/ˈduːti/", "직무, 의무; 관세", "Answering customer inquiries is part of her duties."),
    ("errand", "/ˈɛrənd/", "심부름, 용건", "He stepped out to run a few errands during lunch."),
    ("appointment", "/əˈpɔɪntmənt/", "약속, 예약; 임명", "I have a dental appointment at three o'clock."),
    # ===== 인사 (채용/평가/급여) =====
    ("recruit", "/rɪˈkruːt/", "채용하다, 모집하다", "The company plans to recruit fifty engineers this year."),
    ("recruitment", "/rɪˈkruːtmənt/", "채용, 모집", "The recruitment process includes two rounds of interviews."),
    ("applicant", "/ˈæplɪkənt/", "지원자", "Each applicant must submit a resume and cover letter."),
    ("application", "/ˌæplɪˈkeɪʃən/", "지원(서), 신청(서)", "The deadline for applications is the end of March."),
    ("candidate", "/ˈkændɪˌdeɪt/", "후보자, 지원자", "The final candidates will be interviewed by the director."),
    ("qualification", "/ˌkwɑləfɪˈkeɪʃən/", "자격, 자질", "She has all the qualifications required for the position."),
    ("qualified", "/ˈkwɑləˌfaɪd/", "자격을 갖춘", "Only qualified applicants will be contacted for interviews."),
    ("requirement", "/rɪˈkwaɪrmənt/", "요건, 필요조건", "A driver's license is a requirement for this job."),
    ("reference", "/ˈrɛfərəns/", "추천서, 추천인; 참조", "Please provide two references from previous employers."),
    ("credential", "/krəˈdɛnʃəl/", "자격증, 경력", "His academic credentials impressed the hiring manager."),
    ("expertise", "/ˌɛkspərˈtiːz/", "전문 지식", "We need someone with expertise in digital marketing."),
    ("proficiency", "/prəˈfɪʃənsi/", "숙달, 능숙함", "Proficiency in English is essential for this role."),
    ("competent", "/ˈkɑmpətənt/", "유능한", "She proved to be a highly competent project manager."),
    ("promotion", "/prəˈmoʊʃən/", "승진; 판촉", "He received a promotion after leading the successful project."),
    ("transfer", "/trænsˈfɜːr/", "전근시키다; 옮기다, 이체하다", "She requested a transfer to the Boston office."),
    ("relocate", "/riˈloʊkeɪt/", "이전하다, 이주하다", "The company will relocate its factory to Vietnam."),
    ("resign", "/rɪˈzaɪn/", "사임하다, 사직하다", "The manager resigned after fifteen years with the firm."),
    ("resignation", "/ˌrɛzɪɡˈneɪʃən/", "사직, 사임", "She submitted her resignation letter this morning."),
    ("retirement", "/rɪˈtaɪrmənt/", "은퇴, 퇴직", "The company held a party to celebrate his retirement."),
    ("dismiss", "/dɪsˈmɪs/", "해고하다; (제안을) 일축하다", "He was dismissed for violating company policy."),
    ("layoff", "/ˈleɪˌɔːf/", "정리해고", "The recession forced the company to announce layoffs."),
    ("vacancy", "/ˈveɪkənsi/", "공석, 결원; 빈방", "There is a vacancy in the accounting department."),
    ("opening", "/ˈoʊpənɪŋ/", "공석, 빈자리; 개점", "We currently have two openings for sales representatives."),
    ("salary", "/ˈsæləri/", "급여, 봉급", "The position offers a competitive salary and benefits."),
    ("wage", "/weɪdʒ/", "임금, 시급", "The minimum wage will increase starting next January."),
    ("payroll", "/ˈpeɪroʊl/", "급여 대상자 명단, 급여 지급", "The payroll department handles all salary payments."),
    ("compensation", "/ˌkɑmpənˈseɪʃən/", "보수, 보상(금)", "Employees receive fair compensation for overtime work."),
    ("allowance", "/əˈlaʊəns/", "수당, 비용", "Staff on business trips receive a daily meal allowance."),
    ("incentive", "/ɪnˈsɛntɪv/", "장려금, 유인책", "The company offers incentives to boost sales performance."),
    ("pension", "/ˈpɛnʃən/", "연금", "He receives a monthly pension from his former employer."),
    ("deduction", "/dɪˈdʌkʃən/", "공제(액)", "Tax deductions are shown on your monthly pay statement."),
    ("overtime", "/ˈoʊvərˌtaɪm/", "초과 근무, 야근", "Employees who work overtime are paid extra."),
    ("shift", "/ʃɪft/", "교대 근무; 변화", "She works the night shift at the hospital."),
    ("attendance", "/əˈtɛndəns/", "출석, 참석", "Attendance at the monthly meeting is mandatory."),
    ("punctual", "/ˈpʌŋktʃuəl/", "시간을 지키는", "Employees are expected to be punctual for all meetings."),
    ("evaluation", "/ɪˌvæljuˈeɪʃən/", "평가", "Annual performance evaluations are held in December."),
    ("appraisal", "/əˈpreɪzəl/", "평가, 감정", "Managers conduct staff appraisals twice a year."),
    ("probation", "/proʊˈbeɪʃən/", "수습 기간", "New employees are on probation for three months."),
    ("orientation", "/ˌɔːriənˈteɪʃən/", "예비 교육, 오리엔테이션", "New hires must attend the orientation session on Monday."),
    ("morale", "/məˈræl/", "사기, 의욕", "The bonus program greatly improved employee morale."),
    ("motivate", "/ˈmoʊtəˌveɪt/", "동기를 부여하다", "Good leaders know how to motivate their teams."),
    ("dedication", "/ˌdɛdɪˈkeɪʃən/", "헌신, 전념", "She was praised for her dedication to the project."),
    ("diligent", "/ˈdɪlɪdʒənt/", "성실한, 부지런한", "He is a diligent worker who never misses a deadline."),
    ("supervision", "/ˌsuːpərˈvɪʒən/", "감독, 관리", "Trainees work under the close supervision of a mentor."),
    # ===== 회의 / 의사소통 =====
    ("agenda", "/əˈdʒɛndə/", "안건, 의제", "The budget review is the first item on the agenda."),
    ("minutes", "/ˈmɪnɪts/", "회의록", "The secretary will distribute the minutes of the meeting."),
    ("attendee", "/əˌtɛnˈdiː/", "참석자", "All attendees will receive a copy of the presentation."),
    ("participant", "/pɑːrˈtɪsəpənt/", "참가자", "Participants should register before the workshop begins."),
    ("postpone", "/poʊstˈpoʊn/", "연기하다", "The meeting has been postponed until next Tuesday."),
    ("reschedule", "/riˈskɛdʒuːl/", "일정을 변경하다", "Can we reschedule the interview for Thursday afternoon?"),
    ("convene", "/kənˈviːn/", "(회의를) 소집하다", "The board will convene to elect a new chairperson."),
    ("adjourn", "/əˈdʒɜːrn/", "(회의를) 휴회하다", "The meeting was adjourned until further notice."),
    ("unanimous", "/juˈnænəməs/", "만장일치의", "The proposal was approved by a unanimous vote."),
    ("consensus", "/kənˈsɛnsəs/", "합의, 의견 일치", "The team finally reached a consensus on the design."),
    ("objection", "/əbˈdʒɛkʃən/", "반대, 이의", "Are there any objections to the proposed schedule?"),
    ("proposal", "/prəˈpoʊzəl/", "제안(서)", "The client accepted our proposal for the new campaign."),
    ("presentation", "/ˌpriːzɛnˈteɪʃən/", "발표, 프레젠테이션", "She gave an impressive presentation on market trends."),
    ("briefing", "/ˈbriːfɪŋ/", "브리핑, 상황 설명", "The staff attended a briefing on the new safety rules."),
    ("session", "/ˈsɛʃən/", "(특정 활동) 시간, 회의", "The afternoon session will focus on customer service."),
    ("remark", "/rɪˈmɑːrk/", "발언, 언급", "The CEO made opening remarks at the ceremony."),
    ("announcement", "/əˈnaʊnsmənt/", "발표, 공지", "An official announcement will be made tomorrow morning."),
    ("notify", "/ˈnoʊtəˌfaɪ/", "통지하다, 알리다", "We will notify you of the results by email."),
    ("notification", "/ˌnoʊtəfɪˈkeɪʃən/", "통지, 알림", "You will receive a notification when your order ships."),
    ("memo", "/ˈmɛmoʊ/", "회람, 메모", "A memo about the new dress code was sent to all staff."),
    ("correspondence", "/ˌkɔːrəˈspɑndəns/", "서신, 편지 왕래", "Please keep all correspondence with clients on file."),
    ("inquiry", "/ɪnˈkwaɪəri/", "문의, 질문", "We respond to customer inquiries within 24 hours."),
    ("respond", "/rɪˈspɑnd/", "응답하다, 대응하다", "Please respond to the invitation by Friday."),
    ("confirmation", "/ˌkɑnfərˈmeɪʃən/", "확인(서)", "You will receive a confirmation email after booking."),
    ("reminder", "/rɪˈmaɪndər/", "상기시키는 것, 독촉장", "This is a friendly reminder about tomorrow's deadline."),
    ("clarify", "/ˈklɛrəˌfaɪ/", "명확히 하다", "Could you clarify the terms of the agreement?"),
    ("summarize", "/ˈsʌməˌraɪz/", "요약하다", "Let me summarize the key points of the discussion."),
    ("negotiate", "/nɪˈɡoʊʃiˌeɪt/", "협상하다", "We are negotiating a new contract with the supplier."),
    ("negotiation", "/nɪˌɡoʊʃiˈeɪʃən/", "협상", "The negotiations lasted for more than six hours."),
    ("compromise", "/ˈkɑmprəˌmaɪz/", "타협(하다)", "Both sides agreed to a compromise on the price."),
    ("concession", "/kənˈsɛʃən/", "양보", "The union won several concessions from management."),
    ("persuade", "/pərˈsweɪd/", "설득하다", "He persuaded the board to approve the new budget."),
    ("convince", "/kənˈvɪns/", "확신시키다, 설득하다", "The data convinced investors that the plan would work."),
    ("consult", "/kənˈsʌlt/", "상담하다, 상의하다", "Please consult the manual before calling technical support."),
    ("recommend", "/ˌrɛkəˈmɛnd/", "추천하다, 권고하다", "I recommend that you book your flight early."),
    ("emphasize", "/ˈɛmfəˌsaɪz/", "강조하다", "The trainer emphasized the importance of teamwork."),
    # ===== 계약 / 법률 / 규정 =====
    ("contract", "/ˈkɑntrækt/", "계약(서)", "Both parties signed the contract yesterday afternoon."),
    ("clause", "/klɔːz/", "(계약서의) 조항", "The contract includes a clause about early termination."),
    ("provision", "/prəˈvɪʒən/", "(법률/계약의) 조항, 규정; 공급", "The lease has a provision allowing pets in the building."),
    ("breach", "/briːtʃ/", "위반(하다)", "The company was sued for breach of contract."),
    ("violation", "/ˌvaɪəˈleɪʃən/", "위반", "Parking here is a violation of city regulations."),
    ("comply", "/kəmˈplaɪ/", "(규정을) 준수하다", "All factories must comply with safety regulations."),
    ("compliance", "/kəmˈplaɪəns/", "(규정) 준수", "The audit confirmed compliance with tax laws."),
    ("regulation", "/ˌrɛɡjəˈleɪʃən/", "규정, 규제", "New environmental regulations take effect in June."),
    ("legislation", "/ˌlɛdʒɪsˈleɪʃən/", "법률, 입법", "The new legislation protects part-time workers."),
    ("procedure", "/prəˈsiːdʒər/", "절차", "Please follow the standard procedure for refund requests."),
    ("protocol", "/ˈproʊtəˌkɔːl/", "규약, 의례", "Visitors must follow the security protocol at the entrance."),
    ("permit", "/ˈpɜːrmɪt/", "허가(증); 허가하다", "You need a permit to park in this area."),
    ("license", "/ˈlaɪsəns/", "면허(증), 인가", "The restaurant's business license expires next month."),
    ("authorize", "/ˈɔːθəˌraɪz/", "권한을 부여하다, 인가하다", "Only the manager can authorize large refunds."),
    ("authorization", "/ˌɔːθərəˈzeɪʃən/", "허가, 인가", "Written authorization is required for overtime work."),
    ("approval", "/əˈpruːvəl/", "승인", "The project is awaiting approval from the board."),
    ("valid", "/ˈvælɪd/", "유효한", "This coupon is valid until the end of the month."),
    ("invalid", "/ɪnˈvælɪd/", "무효의", "The ticket is invalid without an official stamp."),
    ("expiration", "/ˌɛkspəˈreɪʃən/", "만료, 만기", "Check the expiration date on your membership card."),
    ("renewal", "/rɪˈnuːəl/", "갱신, 연장", "The lease is up for renewal at the end of the year."),
    ("terminate", "/ˈtɜːrməˌneɪt/", "종료하다, 해지하다", "Either party may terminate the contract with notice."),
    ("termination", "/ˌtɜːrməˈneɪʃən/", "종료, 해지", "The termination of the agreement takes effect in May."),
    ("obligation", "/ˌɑbləˈɡeɪʃən/", "의무", "The buyer has an obligation to pay within thirty days."),
    ("liability", "/ˌlaɪəˈbɪləti/", "법적 책임; 부채", "The company denied liability for the damaged goods."),
    ("liable", "/ˈlaɪəbəl/", "법적 책임이 있는", "Tenants are liable for any damage to the property."),
    ("warranty", "/ˈwɔːrənti/", "품질 보증(서)", "The laptop comes with a two-year warranty."),
    ("confidential", "/ˌkɑnfəˈdɛnʃəl/", "기밀의", "All client information must be kept confidential."),
    ("disclose", "/dɪsˈkloʊz/", "공개하다, 밝히다", "The firm must disclose its financial records to auditors."),
    ("consent", "/kənˈsɛnt/", "동의(하다)", "Written consent is required before sharing personal data."),
    ("dispute", "/dɪˈspjuːt/", "분쟁, 논쟁", "The two companies settled their dispute out of court."),
    ("settlement", "/ˈsɛtəlmənt/", "합의, 해결", "The parties reached a settlement after long negotiations."),
    ("attorney", "/əˈtɜːrni/", "변호사", "Our attorney reviewed the contract before we signed it."),
    ("lawsuit", "/ˈlɔːˌsuːt/", "소송", "The company faces a lawsuit over the faulty product."),
    ("mandatory", "/ˈmændəˌtɔːri/", "의무적인, 필수의", "Safety training is mandatory for all new employees."),
    ("prohibit", "/proʊˈhɪbɪt/", "금지하다", "Smoking is prohibited inside the building."),
    ("restriction", "/rɪˈstrɪkʃən/", "제한, 규제", "There are restrictions on luggage size for this flight."),
    # ===== 재무 / 회계 / 은행 =====
    ("budget", "/ˈbʌdʒɪt/", "예산", "The marketing budget was increased by twenty percent."),
    ("expense", "/ɪkˈspɛns/", "비용, 지출", "Keep all receipts for your travel expenses."),
    ("expenditure", "/ɪkˈspɛndɪtʃər/", "지출, 경비", "The report shows a rise in capital expenditures."),
    ("revenue", "/ˈrɛvəˌnuː/", "수익, 매출", "Annual revenue grew steadily over the past five years."),
    ("profit", "/ˈprɑfɪt/", "이익, 수익", "The company made a large profit from overseas sales."),
    ("profitable", "/ˈprɑfɪtəbəl/", "수익성이 있는", "The new product line proved highly profitable."),
    ("deficit", "/ˈdɛfəsɪt/", "적자, 부족액", "The city is struggling to reduce its budget deficit."),
    ("surplus", "/ˈsɜːrpləs/", "흑자, 잉여", "The trade surplus reached a record high this year."),
    ("asset", "/ˈæsɛt/", "자산", "The building is the company's most valuable asset."),
    ("invoice", "/ˈɪnvɔɪs/", "청구서, 송장", "Please pay the invoice within thirty days of receipt."),
    ("receipt", "/rɪˈsiːt/", "영수증; 수령", "A receipt is required for all refund requests."),
    ("reimburse", "/ˌriːɪmˈbɜːrs/", "(비용을) 환급하다", "The company will reimburse you for travel costs."),
    ("reimbursement", "/ˌriːɪmˈbɜːrsmənt/", "환급, 상환", "Submit the form to request reimbursement for expenses."),
    ("refund", "/ˈriːfʌnd/", "환불(하다)", "You may request a full refund within fourteen days."),
    ("deposit", "/dɪˈpɑzɪt/", "보증금, 예금; 예치하다", "A deposit of one hundred dollars is required to reserve."),
    ("withdraw", "/wɪðˈdrɔː/", "인출하다; 철회하다", "You can withdraw cash at any of our ATMs."),
    ("transaction", "/trænˈzækʃən/", "거래", "All online transactions are protected by encryption."),
    ("remit", "/rɪˈmɪt/", "송금하다", "Please remit payment to the account listed below."),
    ("installment", "/ɪnˈstɔːlmənt/", "할부(금), 분할 불입", "You can pay for the furniture in monthly installments."),
    ("mortgage", "/ˈmɔːrɡɪdʒ/", "주택 담보 대출", "They took out a mortgage to buy their first home."),
    ("loan", "/loʊn/", "대출(금)", "The bank approved a loan for the new equipment."),
    ("debt", "/dɛt/", "빚, 부채", "The firm paid off all its debts within three years."),
    ("owe", "/oʊ/", "빚지고 있다", "We still owe the supplier for last month's shipment."),
    ("currency", "/ˈkɜːrənsi/", "통화, 화폐", "You can exchange currency at the airport counter."),
    ("inflation", "/ɪnˈfleɪʃən/", "물가 상승, 인플레이션", "Rising inflation has increased the cost of raw materials."),
    ("recession", "/rɪˈsɛʃən/", "경기 침체", "Many businesses closed during the economic recession."),
    ("economical", "/ˌɛkəˈnɑmɪkəl/", "경제적인, 절약하는", "This compact car is economical to run and maintain."),
    ("fiscal", "/ˈfɪskəl/", "회계의, 재정의", "The fiscal year ends on the last day of March."),
    ("audit", "/ˈɔːdɪt/", "회계 감사(를 하다)", "The annual audit will begin next Monday."),
    ("accounting", "/əˈkaʊntɪŋ/", "회계", "She works in the accounting department downtown."),
    ("statement", "/ˈsteɪtmənt/", "명세서; 성명", "Your bank statement is available online each month."),
    ("quarterly", "/ˈkwɔːrtərli/", "분기별의", "The quarterly report shows strong sales growth."),
    ("estimate", "/ˈɛstəmət/", "견적(서), 추정(하다)", "The contractor gave us an estimate for the repairs."),
    ("projection", "/prəˈdʒɛkʃən/", "예상, 전망", "Sales projections for next year look very promising."),
    ("forecast", "/ˈfɔːrkæst/", "예측(하다), 전망", "The weather forecast calls for rain this weekend."),
    ("figure", "/ˈfɪɡjər/", "수치; 인물", "The sales figures for December exceeded expectations."),
    ("calculate", "/ˈkælkjəˌleɪt/", "계산하다", "Please calculate the total cost including tax."),
    ("exempt", "/ɪɡˈzɛmpt/", "면제된; 면제하다", "Food items are exempt from the new sales tax."),
    ("dividend", "/ˈdɪvəˌdɛnd/", "배당금", "Shareholders will receive a dividend of two dollars per share."),
    ("shareholder", "/ˈʃɛrˌhoʊldər/", "주주", "The shareholders approved the merger at the annual meeting."),
    ("invest", "/ɪnˈvɛst/", "투자하다", "The firm invested heavily in new technology."),
    ("investment", "/ɪnˈvɛstmənt/", "투자", "Real estate remains a popular long-term investment."),
    ("investor", "/ɪnˈvɛstər/", "투자자", "Foreign investors showed strong interest in the startup."),
    ("fund", "/fʌnd/", "자금(을 대다), 기금", "The government will fund the new highway project."),
    ("capital", "/ˈkæpətəl/", "자본(금); 수도", "The startup raised enough capital to expand overseas."),
    ("bankruptcy", "/ˈbæŋkrʌptsi/", "파산", "The retailer filed for bankruptcy after years of losses."),
    ("lucrative", "/ˈluːkrətɪv/", "수익성이 좋은", "They signed a lucrative deal with a major distributor."),
    # ===== 마케팅 / 영업 / 광고 =====
    ("advertisement", "/ˌædvərˈtaɪzmənt/", "광고", "The company placed an advertisement in the local paper."),
    ("commercial", "/kəˈmɜːrʃəl/", "(TV/라디오) 광고; 상업의", "The new commercial will air during the evening news."),
    ("campaign", "/kæmˈpeɪn/", "캠페인, (광고) 활동", "The ad campaign targets young professionals."),
    ("publicity", "/pʌˈblɪsəti/", "홍보, 언론의 관심", "The event generated a lot of free publicity."),
    ("brochure", "/broʊˈʃʊr/", "(광고용) 소책자", "Pick up a brochure for details about our services."),
    ("flyer", "/ˈflaɪər/", "전단지", "Volunteers handed out flyers about the grand opening."),
    ("catalog", "/ˈkætəˌlɔːɡ/", "카탈로그, 목록", "Our latest catalog features over two hundred products."),
    ("voucher", "/ˈvaʊtʃər/", "상품권, 할인권", "The hotel gave us a voucher for a free breakfast."),
    ("discount", "/ˈdɪskaʊnt/", "할인(하다)", "Members receive a ten percent discount on all items."),
    ("bargain", "/ˈbɑːrɡən/", "싸게 사는 물건; 흥정하다", "This jacket was a real bargain at half price."),
    ("retail", "/ˈriːteɪl/", "소매(의)", "The retail price includes tax and packaging."),
    ("retailer", "/ˈriːteɪlər/", "소매업자", "The retailer offers free delivery on large orders."),
    ("wholesale", "/ˈhoʊlseɪl/", "도매(의)", "We buy directly from the factory at wholesale prices."),
    ("vendor", "/ˈvɛndər/", "판매업체, 노점상", "Several food vendors set up booths at the festival."),
    ("supplier", "/səˈplaɪər/", "공급업체", "We switched to a supplier with faster delivery times."),
    ("merchandise", "/ˈmɜːrtʃənˌdaɪz/", "상품", "All summer merchandise is now on clearance."),
    ("commodity", "/kəˈmɑdəti/", "상품, 원자재", "Coffee is one of the most traded commodities in the world."),
    ("inventory", "/ˈɪnvənˌtɔːri/", "재고 (목록)", "The store closes early today to take inventory."),
    ("demand", "/dɪˈmænd/", "수요; 요구(하다)", "Demand for electric cars continues to grow rapidly."),
    ("consumer", "/kənˈsuːmər/", "소비자", "Consumers are increasingly shopping online."),
    ("clientele", "/ˌklaɪənˈtɛl/", "고객들, 단골", "The boutique serves a wealthy international clientele."),
    ("patron", "/ˈpeɪtrən/", "고객, 후원자", "Regular patrons of the cafe receive loyalty points."),
    ("loyalty", "/ˈlɔɪəlti/", "충성(도)", "The rewards program builds strong customer loyalty."),
    ("subscription", "/səbˈskrɪpʃən/", "구독(료)", "My magazine subscription expires at the end of May."),
    ("questionnaire", "/ˌkwɛstʃəˈnɛr/", "설문지", "Please fill out the questionnaire about our service."),
    ("feedback", "/ˈfiːdbæk/", "의견, 반응", "Customer feedback helped us improve the product design."),
    ("testimonial", "/ˌtɛstəˈmoʊniəl/", "추천 글, 사용 후기", "The website features testimonials from satisfied clients."),
    ("endorse", "/ɪnˈdɔːrs/", "지지하다, (상품을) 홍보하다", "A famous athlete was hired to endorse the sneakers."),
    ("launch", "/lɔːntʃ/", "출시(하다), 개시(하다)", "The company will launch its new smartphone in April."),
    ("release", "/rɪˈliːs/", "출시(하다), 공개(하다)", "The band released its new album last Friday."),
    ("feature", "/ˈfiːtʃər/", "특징(으로 하다), 특집", "The new model features a longer battery life."),
    ("trademark", "/ˈtreɪdˌmɑːrk/", "상표", "The logo is a registered trademark of the company."),
    ("patent", "/ˈpætənt/", "특허(권)", "The inventor filed a patent for his new device."),
    ("competitor", "/kəmˈpɛtətər/", "경쟁사, 경쟁자", "Our prices are lower than those of our competitors."),
    ("competitive", "/kəmˈpɛtətɪv/", "경쟁력 있는, 경쟁적인", "We offer competitive rates on all insurance plans."),
    ("strategy", "/ˈstrætədʒi/", "전략", "The new marketing strategy focuses on social media."),
    ("target", "/ˈtɑːrɡɪt/", "목표(로 삼다), 대상", "The campaign targets customers in their twenties."),
    ("appeal", "/əˈpiːl/", "매력; 호소하다", "The design appeals to younger consumers."),
    ("boost", "/buːst/", "신장시키다, 북돋우다", "The holiday sale boosted revenue significantly."),
    ("expand", "/ɪkˈspænd/", "확장하다", "The chain plans to expand into overseas markets."),
    ("expansion", "/ɪkˈspænʃən/", "확장", "The factory expansion will create hundreds of jobs."),
    # ===== 생산 / 품질 / 시설 =====
    ("manufacture", "/ˌmænjəˈfæktʃər/", "제조하다", "The plant manufactures auto parts for export."),
    ("manufacturer", "/ˌmænjəˈfæktʃərər/", "제조업체", "The manufacturer recalled the defective toasters."),
    ("plant", "/plænt/", "공장; 식물", "The assembly plant operates around the clock."),
    ("facility", "/fəˈsɪləti/", "시설", "The new research facility opens next spring."),
    ("equipment", "/ɪˈkwɪpmənt/", "장비", "All safety equipment must be inspected monthly."),
    ("machinery", "/məˈʃiːnəri/", "기계(류)", "Heavy machinery is used to move the containers."),
    ("appliance", "/əˈplaɪəns/", "가전제품", "The store sells kitchen appliances at discount prices."),
    ("component", "/kəmˈpoʊnənt/", "부품, 구성 요소", "The factory imports electronic components from Japan."),
    ("assemble", "/əˈsɛmbəl/", "조립하다; 모이다", "Workers assemble the furniture before delivery."),
    ("assembly", "/əˈsɛmbli/", "조립; 집회", "The assembly line produces five hundred units a day."),
    ("productivity", "/ˌproʊdʌkˈtɪvəti/", "생산성", "New software greatly improved office productivity."),
    ("output", "/ˈaʊtpʊt/", "생산량, 산출", "Factory output increased by fifteen percent this quarter."),
    ("capacity", "/kəˈpæsəti/", "수용력, 생산 능력", "The stadium was filled to capacity for the final."),
    ("efficient", "/ɪˈfɪʃənt/", "효율적인", "The new engine is more fuel efficient than the old one."),
    ("efficiency", "/ɪˈfɪʃənsi/", "효율(성)", "The upgrade will improve energy efficiency by half."),
    ("streamline", "/ˈstriːmˌlaɪn/", "간소화하다, 능률화하다", "We streamlined the ordering process to save time."),
    ("automate", "/ˈɔːtəˌmeɪt/", "자동화하다", "The warehouse plans to automate its sorting system."),
    ("inspect", "/ɪnˈspɛkt/", "점검하다, 검사하다", "Technicians inspect every unit before shipment."),
    ("inspection", "/ɪnˈspɛkʃən/", "점검, 검사", "The restaurant passed its health inspection easily."),
    ("defect", "/ˈdiːfɛkt/", "결함", "Products with defects are removed from the line."),
    ("defective", "/dɪˈfɛktɪv/", "결함이 있는", "Customers may exchange defective items for new ones."),
    ("flaw", "/flɔː/", "결점, 흠", "Inspectors found a flaw in the metal casing."),
    ("malfunction", "/ˌmælˈfʌŋkʃən/", "오작동(하다)", "The elevator malfunctioned and stopped between floors."),
    ("repair", "/rɪˈpɛr/", "수리(하다)", "The copier is being repaired and will be ready tomorrow."),
    ("maintain", "/meɪnˈteɪn/", "유지하다, 정비하다", "It is important to maintain the equipment regularly."),
    ("maintenance", "/ˈmeɪntənəns/", "유지 보수, 정비", "The elevator is out of service for routine maintenance."),
    ("durable", "/ˈdʊrəbəl/", "내구성이 있는", "These work boots are made of durable leather."),
    ("sturdy", "/ˈstɜːrdi/", "튼튼한", "The shelves are sturdy enough to hold heavy boxes."),
    ("fragile", "/ˈfrædʒəl/", "깨지기 쉬운", "Mark the box as fragile before shipping it."),
    ("precision", "/prɪˈsɪʒən/", "정밀(성)", "The parts are cut with laser precision."),
    ("specification", "/ˌspɛsəfɪˈkeɪʃən/", "사양, 설계 명세", "The product was built exactly to the client's specifications."),
    ("warehouse", "/ˈwɛrˌhaʊs/", "창고", "The goods are stored in a warehouse near the port."),
    ("storage", "/ˈstɔːrɪdʒ/", "보관, 저장", "The office rents extra storage space in the basement."),
    ("utility", "/juˈtɪləti/", "공공요금, 공익 설비", "Utilities such as water and gas are included in the rent."),
    # ===== 물류 / 배송 / 무역 =====
    ("shipment", "/ˈʃɪpmənt/", "수송(품), 배송", "The shipment of office chairs arrived this morning."),
    ("courier", "/ˈkʊriər/", "택배 회사, 배달원", "The documents were sent by overnight courier."),
    ("freight", "/freɪt/", "화물 (운송)", "Freight costs have risen due to fuel prices."),
    ("cargo", "/ˈkɑːrɡoʊ/", "화물", "The ship carries cargo between Busan and Los Angeles."),
    ("carrier", "/ˈkæriər/", "운송 회사, 항공사", "Choose your preferred carrier at checkout."),
    ("dispatch", "/dɪˈspætʃ/", "발송하다, 파견하다", "Your order will be dispatched within two business days."),
    ("distribute", "/dɪˈstrɪbjuːt/", "유통시키다, 나눠주다", "The firm distributes medical supplies nationwide."),
    ("distribution", "/ˌdɪstrəˈbjuːʃən/", "유통, 분배", "The company built a new distribution center in Texas."),
    ("export", "/ˈɛkspɔːrt/", "수출(하다)", "The country exports mainly cars and electronics."),
    ("import", "/ˈɪmpɔːrt/", "수입(하다)", "The store imports cheese directly from France."),
    ("customs", "/ˈkʌstəmz/", "세관", "All luggage must pass through customs at the airport."),
    ("tariff", "/ˈtærɪf/", "관세", "New tariffs on steel raised construction costs."),
    ("logistics", "/loʊˈdʒɪstɪks/", "물류", "She manages logistics for the entire supply chain."),
    ("expedite", "/ˈɛkspəˌdaɪt/", "신속히 처리하다", "We can expedite your order for an extra fee."),
    ("promptly", "/ˈprɑmptli/", "즉시, 제시간에", "Please reply promptly to confirm your attendance."),
    ("destination", "/ˌdɛstəˈneɪʃən/", "목적지", "The package reached its destination in three days."),
    ("recipient", "/rɪˈsɪpiənt/", "수령인, 받는 사람", "The recipient must sign for the registered mail."),
    ("parcel", "/ˈpɑːrsəl/", "소포", "A parcel arrived for you while you were out."),
    ("packaging", "/ˈpækɪdʒɪŋ/", "포장(재)", "The new packaging is made from recycled paper."),
    ("crate", "/kreɪt/", "나무 상자", "The machine parts were shipped in wooden crates."),
    ("container", "/kənˈteɪnər/", "컨테이너, 용기", "Hundreds of containers are unloaded at the dock daily."),
    ("load", "/loʊd/", "싣다; 짐", "Workers loaded the truck with boxes of produce."),
    ("transit", "/ˈtrænzɪt/", "운송, 통과", "The vase was damaged in transit."),
    ("via", "/ˈvaɪə/", "~을 경유하여, ~을 통해", "The flight goes to London via Frankfurt."),
    ("enclose", "/ɪnˈkloʊz/", "동봉하다", "Please find enclosed a copy of the invoice."),
    ("attachment", "/əˈtætʃmənt/", "첨부 (파일)", "See the attachment for the full price list."),
    ("forward", "/ˈfɔːrwərd/", "전달하다, 회송하다", "Please forward this email to the sales team."),
    # ===== 여행 / 출장 / 교통 =====
    ("itinerary", "/aɪˈtɪnəˌrɛri/", "여행 일정(표)", "The travel agent emailed me a detailed itinerary."),
    ("reservation", "/ˌrɛzərˈveɪʃən/", "예약", "I made a reservation for a table for four."),
    ("accommodation", "/əˌkɑməˈdeɪʃən/", "숙박 시설", "The conference fee includes meals and accommodations."),
    ("accommodate", "/əˈkɑməˌdeɪt/", "수용하다; 편의를 봐주다", "The hall can accommodate up to three hundred guests."),
    ("lodging", "/ˈlɑdʒɪŋ/", "숙소", "The company covers lodging expenses for business trips."),
    ("amenity", "/əˈmɛnəti/", "편의 시설", "The hotel's amenities include a pool and a gym."),
    ("occupancy", "/ˈɑkjəpənsi/", "(호텔) 이용률, 점유", "Hotel occupancy rates peak during the summer."),
    ("concierge", "/ˌkɑnsiˈɛrʒ/", "(호텔) 안내 직원", "The concierge can arrange tickets for the show."),
    ("complimentary", "/ˌkɑmpləˈmɛntəri/", "무료의; 칭찬하는", "Guests receive a complimentary breakfast each morning."),
    ("courtesy", "/ˈkɜːrtəsi/", "호의, 예의; 무료의", "A courtesy shuttle runs between the hotel and airport."),
    ("hospitality", "/ˌhɑspəˈtæləti/", "환대, 접객(업)", "The staff is known for its warm hospitality."),
    ("departure", "/dɪˈpɑːrtʃər/", "출발", "Please arrive two hours before your departure time."),
    ("layover", "/ˈleɪˌoʊvər/", "경유, 도중하차", "We have a three-hour layover in Tokyo."),
    ("boarding", "/ˈbɔːrdɪŋ/", "탑승", "Boarding will begin at gate twelve in ten minutes."),
    ("aisle", "/aɪl/", "통로", "Would you prefer a window or an aisle seat?"),
    ("luggage", "/ˈlʌɡɪdʒ/", "짐, 수하물", "Each passenger may check two pieces of luggage."),
    ("baggage", "/ˈbæɡɪdʒ/", "수하물", "Oversized baggage requires an additional fee."),
    ("carry-on", "/ˈkæri ˌɔːn/", "기내 반입 수하물", "Only one carry-on bag is allowed per passenger."),
    ("declare", "/dɪˈklɛr/", "(세관에) 신고하다; 선언하다", "Do you have anything to declare at customs?"),
    ("embassy", "/ˈɛmbəsi/", "대사관", "Contact the embassy if you lose your passport abroad."),
    ("fare", "/fɛr/", "(교통) 요금", "Bus fares will increase by ten percent next month."),
    ("round-trip", "/ˌraʊnd ˈtrɪp/", "왕복 여행(의)", "A round-trip ticket is cheaper than two one-way tickets."),
    ("commute", "/kəˈmjuːt/", "통근(하다)", "She commutes to the city by train every day."),
    ("commuter", "/kəˈmjuːtər/", "통근자", "The new subway line will benefit thousands of commuters."),
    ("passenger", "/ˈpæsəndʒər/", "승객", "Passengers must fasten their seat belts during takeoff."),
    ("pedestrian", "/pəˈdɛstriən/", "보행자", "This street is closed to traffic for pedestrian safety."),
    ("detour", "/ˈdiːtʊr/", "우회(로)", "Drivers must take a detour due to road construction."),
    ("congestion", "/kənˈdʒɛstʃən/", "혼잡, 정체", "Traffic congestion is worst during rush hour."),
    ("intersection", "/ˌɪntərˈsɛkʃən/", "교차로", "Turn left at the next intersection."),
    ("vehicle", "/ˈviːɪkəl/", "차량", "Unauthorized vehicles will be towed at the owner's expense."),
    ("proximity", "/prɑkˈsɪməti/", "가까움, 근접", "The hotel's proximity to the station makes it convenient."),
    # ===== 식당 / 쇼핑 =====
    ("cuisine", "/kwɪˈziːn/", "요리(법)", "The restaurant is famous for its Italian cuisine."),
    ("beverage", "/ˈbɛvərɪdʒ/", "음료", "The ticket includes snacks and beverages."),
    ("ingredient", "/ɪnˈɡriːdiənt/", "재료, 성분", "The chef uses only fresh local ingredients."),
    ("appetizer", "/ˈæpəˌtaɪzər/", "전채 요리, 애피타이저", "We ordered two appetizers to share before the meal."),
    ("portion", "/ˈpɔːrʃən/", "1인분, 몫", "The portions at this restaurant are quite generous."),
    ("utensil", "/juˈtɛnsəl/", "(주방) 도구", "Cooking utensils are stored in the bottom drawer."),
    ("banquet", "/ˈbæŋkwɪt/", "연회", "The awards banquet will be held in the grand ballroom."),
    ("catering", "/ˈkeɪtərɪŋ/", "출장 요리 (서비스)", "We hired a catering service for the office party."),
    ("buffet", "/bəˈfeɪ/", "뷔페", "The hotel serves a breakfast buffet until ten."),
    ("gratuity", "/ɡrəˈtuːəti/", "팁, 봉사료", "A fifteen percent gratuity is added for large groups."),
    ("apparel", "/əˈpærəl/", "의류", "The store specializes in outdoor apparel."),
    ("garment", "/ˈɡɑːrmənt/", "의복, 옷", "Delicate garments should be washed by hand."),
    ("fabric", "/ˈfæbrɪk/", "직물, 천", "This fabric is soft and easy to clean."),
    ("textile", "/ˈtɛkstaɪl/", "직물, 섬유", "The city was once a center of the textile industry."),
    ("alteration", "/ˌɔːltəˈreɪʃən/", "수선; 변경", "The store offers free alterations on all suits."),
    ("tailor", "/ˈteɪlər/", "재단사; 맞추다", "The tailor shortened the sleeves of my jacket."),
    ("restock", "/riˈstɑk/", "재입고하다", "The item will be restocked early next week."),
    ("purchase", "/ˈpɜːrtʃəs/", "구입(하다)", "Keep your receipt as proof of purchase."),
    ("exchange", "/ɪksˈtʃeɪndʒ/", "교환(하다)", "You may exchange the item within thirty days."),
    # ===== 부동산 / 건설 =====
    ("property", "/ˈprɑpərti/", "부동산, 재산", "The property includes a house and a large garden."),
    ("tenant", "/ˈtɛnənt/", "세입자", "Tenants must give thirty days notice before moving out."),
    ("landlord", "/ˈlændlɔːrd/", "집주인, 임대인", "The landlord agreed to repaint the apartment."),
    ("lease", "/liːs/", "임대차 계약(을 하다)", "We signed a two-year lease on the office space."),
    ("rental", "/ˈrɛntəl/", "임대(료), 대여", "Car rental rates are higher during the holidays."),
    ("furnished", "/ˈfɜːrnɪʃt/", "가구가 비치된", "The apartment comes fully furnished."),
    ("spacious", "/ˈspeɪʃəs/", "넓은", "The office is spacious enough for twenty desks."),
    ("renovate", "/ˈrɛnəˌveɪt/", "개조하다, 보수하다", "The lobby is being renovated this summer."),
    ("renovation", "/ˌrɛnəˈveɪʃən/", "개조, 보수 공사", "The museum will close for renovations until May."),
    ("remodel", "/riˈmɑdəl/", "개조하다", "They remodeled the kitchen with new cabinets."),
    ("refurbish", "/riˈfɜːrbɪʃ/", "재단장하다", "The hotel was completely refurbished last year."),
    ("restore", "/rɪˈstɔːr/", "복원하다, 회복시키다", "Workers restored the historic theater to its original state."),
    ("construction", "/kənˈstrʌkʃən/", "건설, 공사", "The bridge is under construction until October."),
    ("contractor", "/ˈkɑntræktər/", "계약자, 시공업체", "The contractor finished the project ahead of schedule."),
    ("architect", "/ˈɑːrkəˌtɛkt/", "건축가", "A famous architect designed the new city library."),
    ("blueprint", "/ˈbluːˌprɪnt/", "설계도, 청사진", "The engineers reviewed the blueprints for the tower."),
    ("foundation", "/faʊnˈdeɪʃən/", "토대, 기초; 재단", "Workers poured the foundation for the new building."),
    ("demolish", "/dɪˈmɑlɪʃ/", "철거하다", "The old warehouse will be demolished next month."),
    ("install", "/ɪnˈstɔːl/", "설치하다", "Technicians will install the new air conditioner today."),
    ("installation", "/ˌɪnstəˈleɪʃən/", "설치", "Installation of the software takes about ten minutes."),
    ("plumbing", "/ˈplʌmɪŋ/", "배관 (설비)", "The plumbing in this building needs to be replaced."),
    ("electrician", "/ɪˌlɛkˈtrɪʃən/", "전기 기사", "An electrician came to fix the faulty wiring."),
    ("carpenter", "/ˈkɑːrpəntər/", "목수", "The carpenter built custom shelves for the study."),
    ("landscaping", "/ˈlændˌskeɪpɪŋ/", "조경", "The landscaping around the office looks beautiful."),
    ("premises", "/ˈprɛmɪsɪz/", "부지, 구내", "Smoking is not allowed anywhere on the premises."),
    ("corridor", "/ˈkɔːrədər/", "복도", "The meeting room is at the end of the corridor."),
    ("auditorium", "/ˌɔːdəˈtɔːriəm/", "강당", "The lecture will be held in the main auditorium."),
    ("venue", "/ˈvɛnjuː/", "(행사) 장소", "The wedding venue can host up to two hundred guests."),
    # ===== 병원 / 보험 / 일상 =====
    ("pharmacy", "/ˈfɑːrməsi/", "약국", "The pharmacy is open until nine on weekdays."),
    ("prescription", "/prɪˈskrɪpʃən/", "처방(전)", "This medicine is available only by prescription."),
    ("prescribe", "/prɪˈskraɪb/", "처방하다", "The doctor prescribed antibiotics for the infection."),
    ("physician", "/fɪˈzɪʃən/", "(내과) 의사", "Consult your physician before starting a new diet."),
    ("checkup", "/ˈtʃɛkˌʌp/", "건강 검진", "Employees receive a free annual checkup."),
    ("diagnose", "/ˈdaɪəɡˌnoʊs/", "진단하다", "The illness was diagnosed at an early stage."),
    ("symptom", "/ˈsɪmptəm/", "증상", "Common symptoms include fever and a sore throat."),
    ("treatment", "/ˈtriːtmənt/", "치료(법); 대우", "The new treatment has shown promising results."),
    ("remedy", "/ˈrɛmədi/", "치료(약), 해결책", "Rest is often the best remedy for a cold."),
    ("recovery", "/rɪˈkʌvəri/", "회복", "We wish you a quick recovery from your surgery."),
    ("insurance", "/ɪnˈʃʊrəns/", "보험", "The company provides health insurance for all staff."),
    ("coverage", "/ˈkʌvərɪdʒ/", "보장 (범위); 보도", "The policy offers full coverage for medical expenses."),
    ("premium", "/ˈpriːmiəm/", "보험료; 고급의", "Monthly premiums will rise slightly next year."),
    ("nutrition", "/nuˈtrɪʃən/", "영양", "Good nutrition is essential for staying healthy."),
    ("hygiene", "/ˈhaɪdʒiːn/", "위생", "Food handlers must follow strict hygiene rules."),
    ("sanitary", "/ˈsænəˌtɛri/", "위생적인", "The kitchen is kept in a sanitary condition."),
    ("fatigue", "/fəˈtiːɡ/", "피로", "Fatigue can lead to mistakes in the workplace."),
    # ===== 사무기기 / IT =====
    ("photocopier", "/ˈfoʊtoʊˌkɑpiər/", "복사기", "The photocopier on the third floor is out of order."),
    ("duplicate", "/ˈduːplɪkət/", "사본; 복제하다", "Please make a duplicate of the signed contract."),
    ("stationery", "/ˈsteɪʃəˌnɛri/", "문구류", "Order more stationery from the office supply store."),
    ("bulletin", "/ˈbʊlətən/", "게시, 공고", "Check the bulletin board for the updated schedule."),
    ("extension", "/ɪkˈstɛnʃən/", "내선 번호; 연장", "Call me at extension two-four-seven."),
    ("operator", "/ˈɑpəˌreɪtər/", "전화 교환원; 조작자", "Dial zero to speak with an operator."),
    ("voicemail", "/ˈvɔɪsˌmeɪl/", "음성 메시지", "Please leave a voicemail if I miss your call."),
    ("teleconference", "/ˈtɛləˌkɑnfərəns/", "화상/전화 회의", "The teams held a teleconference across three time zones."),
    ("database", "/ˈdeɪtəˌbeɪs/", "데이터베이스", "Customer records are stored in a secure database."),
    ("compatible", "/kəmˈpætəbəl/", "호환되는", "The printer is compatible with most laptops."),
    ("troubleshoot", "/ˈtrʌbəlˌʃuːt/", "문제를 해결하다", "The technician will troubleshoot the network issue."),
    ("glitch", "/ɡlɪtʃ/", "작은 결함, 오류", "A software glitch delayed the online orders."),
    ("retrieve", "/rɪˈtriːv/", "되찾다, (정보를) 검색하다", "You can retrieve deleted files from the backup."),
    ("archive", "/ˈɑːrkaɪv/", "보관소; 보관하다", "Old records are archived in the basement."),
    ("manual", "/ˈmænjuəl/", "설명서; 수동의", "Read the instruction manual before using the machine."),
    # ===== 빈출 동사 =====
    ("implement", "/ˈɪmpləˌmɛnt/", "시행하다, 실행하다", "The company will implement the new policy in July."),
    ("facilitate", "/fəˈsɪləˌteɪt/", "용이하게 하다, 촉진하다", "The new system facilitates communication between teams."),
    ("coordinate", "/koʊˈɔːrdəˌneɪt/", "조율하다, 조정하다", "She coordinates events for the marketing department."),
    ("collaborate", "/kəˈlæbəˌreɪt/", "협력하다", "The two firms collaborated on the research project."),
    ("delegate", "/ˈdɛləˌɡeɪt/", "위임하다; 대표", "Good managers know how to delegate tasks effectively."),
    ("designate", "/ˈdɛzɪɡˌneɪt/", "지정하다, 지명하다", "This area is designated for visitor parking."),
    ("appoint", "/əˈpɔɪnt/", "임명하다", "She was appointed head of the finance division."),
    ("assign", "/əˈsaɪn/", "배정하다, 맡기다", "Each intern is assigned a mentor for guidance."),
    ("allocate", "/ˈæləˌkeɪt/", "할당하다, 배분하다", "More funds were allocated to employee training."),
    ("ensure", "/ɪnˈʃʊr/", "보장하다, 반드시 ~하게 하다", "Please ensure that all windows are locked before leaving."),
    ("verify", "/ˈvɛrəˌfaɪ/", "확인하다, 검증하다", "Please verify your address before submitting the order."),
    ("assess", "/əˈsɛs/", "평가하다", "The committee will assess each proposal carefully."),
    ("evaluate", "/ɪˈvæljuˌeɪt/", "평가하다", "Supervisors evaluate employee performance every quarter."),
    ("determine", "/dɪˈtɜːrmɪn/", "결정하다, 알아내다", "An inspection will determine the cause of the leak."),
    ("identify", "/aɪˈdɛntəˌfaɪ/", "확인하다, 찾아내다", "The survey helped identify areas for improvement."),
    ("indicate", "/ˈɪndɪˌkeɪt/", "나타내다, 보여주다", "The results indicate a growing demand for our services."),
    ("demonstrate", "/ˈdɛmənˌstreɪt/", "보여주다, 시연하다", "The salesperson demonstrated how the blender works."),
    ("exhibit", "/ɪɡˈzɪbɪt/", "전시하다; 전시(품)", "The gallery exhibits works by local artists."),
    ("highlight", "/ˈhaɪˌlaɪt/", "강조하다; 하이라이트", "The report highlights the need for more staff."),
    ("prioritize", "/praɪˈɔːrəˌtaɪz/", "우선순위를 정하다", "Learn to prioritize tasks when deadlines overlap."),
    ("specialize", "/ˈspɛʃəˌlaɪz/", "전문으로 하다", "The firm specializes in corporate law."),
    ("undergo", "/ˌʌndərˈɡoʊ/", "겪다, 받다", "The building will undergo major repairs this fall."),
    ("undertake", "/ˌʌndərˈteɪk/", "착수하다, 맡다", "The city undertook a project to widen the roads."),
    ("oversee", "/ˌoʊvərˈsiː/", "감독하다", "She oversees daily operations at the warehouse."),
    ("monitor", "/ˈmɑnətər/", "관찰하다, 감시하다", "Managers monitor progress through weekly reports."),
    ("conduct", "/kənˈdʌkt/", "수행하다, 실시하다", "The team conducted a survey of customer preferences."),
    ("achieve", "/əˈtʃiːv/", "달성하다", "We achieved our sales target two months early."),
    ("accomplish", "/əˈkɑmplɪʃ/", "성취하다, 해내다", "The team accomplished the task ahead of schedule."),
    ("attain", "/əˈteɪn/", "이루다, 획득하다", "She attained the rank of senior manager in five years."),
    ("exceed", "/ɪkˈsiːd/", "초과하다, 넘어서다", "Ticket sales exceeded all expectations."),
    ("surpass", "/sərˈpæs/", "능가하다", "This year's profits surpassed last year's record."),
    ("enhance", "/ɪnˈhæns/", "향상시키다", "The upgrade will enhance the system's security."),
    ("optimize", "/ˈɑptəˌmaɪz/", "최적화하다", "We optimized the website for mobile devices."),
    ("maximize", "/ˈmæksəˌmaɪz/", "극대화하다", "The layout was changed to maximize floor space."),
    ("minimize", "/ˈmɪnəˌmaɪz/", "최소화하다", "Safety checks minimize the risk of accidents."),
    ("fluctuate", "/ˈflʌktʃuˌeɪt/", "변동하다, 오르내리다", "Fuel prices fluctuate depending on the season."),
    ("stabilize", "/ˈsteɪbəˌlaɪz/", "안정되다, 안정시키다", "The market stabilized after weeks of uncertainty."),
    ("retain", "/rɪˈteɪn/", "유지하다, 보유하다", "Good benefits help the company retain skilled workers."),
    ("obtain", "/əbˈteɪn/", "얻다, 획득하다", "Visitors must obtain a pass at the front desk."),
    ("acquire", "/əˈkwaɪər/", "인수하다, 획득하다", "The corporation acquired a smaller rival last year."),
    ("secure", "/sɪˈkjʊr/", "확보하다; 안전한", "The startup secured funding from three investors."),
    ("procure", "/proʊˈkjʊr/", "조달하다, 구하다", "The department procures supplies for all branches."),
    ("anticipate", "/ænˈtɪsəˌpeɪt/", "예상하다, 기대하다", "We anticipate strong demand for the new model."),
    ("acknowledge", "/ækˈnɑlɪdʒ/", "인정하다; 받았음을 알리다", "Please acknowledge receipt of this email."),
    ("compensate", "/ˈkɑmpənˌseɪt/", "보상하다", "The airline compensated passengers for the delay."),
    ("waive", "/weɪv/", "(권리/요금을) 면제하다", "The bank waived the fee for first-time customers."),
    ("adhere", "/ædˈhɪr/", "(규칙을) 지키다, 부착되다", "All staff must adhere to the dress code."),
    ("assure", "/əˈʃʊr/", "장담하다, 확언하다", "The manager assured us that the issue would be fixed."),
    # ===== 빈출 형용사 =====
    ("upcoming", "/ˈʌpˌkʌmɪŋ/", "다가오는, 곧 있을", "Details about the upcoming seminar will be posted soon."),
    ("tentative", "/ˈtɛntətɪv/", "잠정적인", "We set a tentative date for the product launch."),
    ("optional", "/ˈɑpʃənəl/", "선택적인", "Attendance at the evening session is optional."),
    ("eligible", "/ˈɛlɪdʒəbəl/", "자격이 있는", "Full-time employees are eligible for the bonus."),
    ("accessible", "/ækˈsɛsəbəl/", "접근 가능한, 이용하기 쉬운", "The building is accessible by wheelchair."),
    ("affordable", "/əˈfɔːrdəbəl/", "(가격이) 알맞은", "The store offers affordable furniture for students."),
    ("reasonable", "/ˈriːzənəbəl/", "합리적인, 적당한", "The hotel offers clean rooms at reasonable prices."),
    ("adjacent", "/əˈdʒeɪsənt/", "인접한", "The parking lot is adjacent to the main entrance."),
    ("sufficient", "/səˈfɪʃənt/", "충분한", "We have sufficient supplies for the entire event."),
    ("insufficient", "/ˌɪnsəˈfɪʃənt/", "불충분한", "The project was delayed due to insufficient funding."),
    ("adequate", "/ˈædɪkwət/", "적절한, 충분한", "Make sure there is adequate lighting in the workspace."),
    ("numerous", "/ˈnuːmərəs/", "수많은", "We received numerous applications for the position."),
    ("diverse", "/dɪˈvɜːrs/", "다양한", "The company has a diverse team from many countries."),
    ("entire", "/ɪnˈtaɪər/", "전체의", "The entire staff attended the year-end party."),
    ("initial", "/ɪˈnɪʃəl/", "처음의, 초기의", "The initial response to the product was positive."),
    ("mutual", "/ˈmjuːtʃuəl/", "상호간의", "The contract was ended by mutual agreement."),
    ("prospective", "/prəˈspɛktɪv/", "장래의, 유망한", "Prospective buyers can tour the model home."),
    ("prominent", "/ˈprɑmənənt/", "저명한, 두드러진", "A prominent economist will speak at the forum."),
    ("renowned", "/rɪˈnaʊnd/", "유명한, 명성 있는", "The hotel hired a renowned chef from Paris."),
    ("prestigious", "/prɛˈstɪdʒəs/", "명망 있는", "She won a prestigious award for her research."),
    ("reputable", "/ˈrɛpjətəbəl/", "평판이 좋은", "Buy electronics only from reputable dealers."),
    ("innovative", "/ˈɪnəˌveɪtɪv/", "혁신적인", "The firm is known for its innovative designs."),
    ("state-of-the-art", "/ˌsteɪt əv ði ˈɑːrt/", "최첨단의", "The lab is equipped with state-of-the-art instruments."),
    ("sophisticated", "/səˈfɪstɪˌkeɪtɪd/", "정교한, 세련된", "The security system uses sophisticated sensors."),
    ("comprehensive", "/ˌkɑmprɪˈhɛnsɪv/", "포괄적인, 종합적인", "The manual provides comprehensive instructions."),
    ("extensive", "/ɪkˈstɛnsɪv/", "광범위한, 폭넓은", "She has extensive experience in international trade."),
    ("crucial", "/ˈkruːʃəl/", "결정적인, 중대한", "Timing is crucial when launching a new product."),
    ("essential", "/ɪˈsɛnʃəl/", "필수적인", "Teamwork is essential to the project's success."),
    ("imperative", "/ɪmˈpɛrətɪv/", "반드시 해야 하는, 긴요한", "It is imperative that the report be finished today."),
    ("feasible", "/ˈfiːzəbəl/", "실현 가능한", "The engineers confirmed the plan was feasible."),
    ("viable", "/ˈvaɪəbəl/", "실행 가능한, 성공할 수 있는", "Solar power is a viable alternative for the factory."),
    ("promising", "/ˈprɑmɪsɪŋ/", "유망한, 촉망되는", "The trial results look very promising."),
    ("outstanding", "/aʊtˈstændɪŋ/", "뛰어난; 미지불된", "She received an award for outstanding service."),
    ("exceptional", "/ɪkˈsɛpʃənəl/", "탁월한, 이례적인", "The restaurant is known for exceptional service."),
    ("impressive", "/ɪmˈprɛsɪv/", "인상적인", "The intern made an impressive presentation."),
    ("notable", "/ˈnoʊtəbəl/", "주목할 만한", "The conference attracted several notable speakers."),
    ("preliminary", "/prɪˈlɪməˌnɛri/", "예비의", "Preliminary results will be announced on Friday."),
    ("subsequent", "/ˈsʌbsɪkwənt/", "그 다음의, 이후의", "Subsequent orders will ship free of charge."),
    ("consecutive", "/kənˈsɛkjətɪv/", "연속적인", "Sales rose for the third consecutive quarter."),
    ("temporary", "/ˈtɛmpəˌrɛri/", "일시적인, 임시의", "The office hired temporary staff for the busy season."),
    ("permanent", "/ˈpɜːrmənənt/", "영구적인, 정규의", "After six months, she was offered a permanent position."),
    ("exclusive", "/ɪkˈskluːsɪv/", "독점적인, 전용의", "Members enjoy exclusive access to the lounge."),
    ("informative", "/ɪnˈfɔːrmətɪv/", "유익한", "The workshop was both informative and enjoyable."),
    # ===== 빈출 부사 / 전치사 =====
    ("additionally", "/əˈdɪʃənəli/", "게다가, 추가로", "Additionally, all attendees will receive a free gift."),
    ("approximately", "/əˈprɑksəmətli/", "대략", "The flight takes approximately eleven hours."),
    ("currently", "/ˈkɜːrəntli/", "현재", "The position is currently open to internal applicants."),
    ("previously", "/ˈpriːviəsli/", "이전에", "She previously worked at an advertising agency."),
    ("subsequently", "/ˈsʌbsɪkwəntli/", "그 후에", "He joined as an intern and subsequently became CEO."),
    ("thoroughly", "/ˈθɜːroʊli/", "철저히", "Please review the contract thoroughly before signing."),
    ("temporarily", "/ˌtɛmpəˈrɛrəli/", "일시적으로", "The service is temporarily unavailable due to maintenance."),
    ("exclusively", "/ɪkˈskluːsɪvli/", "독점적으로, 오로지", "This offer is available exclusively to members."),
    ("significantly", "/sɪɡˈnɪfɪkəntli/", "상당히", "Production costs dropped significantly last year."),
    ("substantially", "/səbˈstænʃəli/", "상당히, 크게", "The budget was substantially increased for research."),
    ("considerably", "/kənˈsɪdərəbli/", "상당히", "The commute is considerably shorter by subway."),
    ("remarkably", "/rɪˈmɑːrkəbli/", "놀랍도록, 두드러지게", "The team finished the project remarkably quickly."),
    ("particularly", "/pərˈtɪkjələrli/", "특히", "Sales were particularly strong in the Asian market."),
    ("primarily", "/praɪˈmɛrəli/", "주로", "The fund is used primarily for staff training."),
    ("frequently", "/ˈfriːkwəntli/", "자주", "Schedules are updated frequently on our website."),
    ("rarely", "/ˈrɛrli/", "드물게", "He rarely misses the morning meeting."),
    ("immediately", "/ɪˈmiːdiətli/", "즉시", "Please report any accidents immediately."),
    ("shortly", "/ˈʃɔːrtli/", "곧, 얼마 안 되어", "The manager will be with you shortly."),
    ("momentarily", "/ˌmoʊmənˈtɛrəli/", "곧; 잠깐", "The train will be departing momentarily."),
    ("accordingly", "/əˈkɔːrdɪŋli/", "그에 맞게, 따라서", "Prices vary by season; plan your budget accordingly."),
    ("consequently", "/ˈkɑnsəˌkwɛntli/", "그 결과, 따라서", "The flight was delayed; consequently, we missed the event."),
    ("furthermore", "/ˈfɜːrðərˌmɔːr/", "더욱이, 게다가", "Furthermore, the plan will reduce operating costs."),
    ("nevertheless", "/ˌnɛvərðəˈlɛs/", "그럼에도 불구하고", "The task was difficult; nevertheless, we finished on time."),
    ("otherwise", "/ˈʌðərˌwaɪz/", "그렇지 않으면; 달리", "Leave now; otherwise you will miss the train."),
    ("meanwhile", "/ˈmiːnˌwaɪl/", "그동안에, 한편", "Meanwhile, the design team worked on the packaging."),
    ("whereas", "/wɛrˈæz/", "~인 반면에", "Sales rose in Asia, whereas they fell in Europe."),
    ("despite", "/dɪˈspaɪt/", "~에도 불구하고", "Despite the rain, the outdoor event went ahead."),
    ("regarding", "/rɪˈɡɑːrdɪŋ/", "~에 관하여", "Please contact us regarding any billing questions."),
    ("concerning", "/kənˈsɜːrnɪŋ/", "~에 관한", "He asked several questions concerning the contract."),
    ("prior to", "", "~에 앞서, ~전에", "Please arrive thirty minutes prior to the interview."),
    ("in advance", "", "미리, 사전에", "Tickets must be purchased at least a week in advance."),
    ("on behalf of", "", "~을 대신하여, ~을 대표하여", "She accepted the award on behalf of the whole team."),
    ("in accordance with", "", "~에 따라", "All work is done in accordance with safety standards."),
    ("with regard to", "", "~에 관해서", "We have no complaints with regard to the service."),
    ("as of", "", "~부로, ~현재로", "As of next Monday, the new hours take effect."),
]

# ---------- 생성 로직 ----------
def load_existing_words():
    src = os.path.join(BASE, "영어단어장.csv")
    existing = set()
    with open(src, encoding="utf-8-sig", newline="") as f:
        for row in csv.reader(f):
            if row and row[0].strip():
                existing.add(row[0].strip().lower())
    return existing

def main():
    existing = load_existing_words()
    seen = set()
    words = []
    skipped = []
    for w, ipa, meaning, example in TOEIC:
        key = w.lower()
        if key in existing:
            skipped.append(w)
            continue
        if key in seen:
            continue
        seen.add(key)
        words.append({
            "id": 10000 + len(words) + 1,
            "word": w,
            "ipa": ipa,
            "meaning": meaning,
            "example": example,
            "deck": "toeic",
        })

    dst = os.path.join(BASE, "data", "words_toeic.js")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("// 자동 생성 파일 - TOEIC 빈출 어휘. 재생성: python build_toeic.py\n")
        f.write("const WORDS_TOEIC = ")
        json.dump(words, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")

    print(f"TOEIC 단어 {len(words)}개 생성 -> {dst}")
    if skipped:
        print(f"내 단어장과 중복되어 제외: {len(skipped)}개 ({', '.join(skipped[:10])}...)")

if __name__ == "__main__":
    main()
